name = "witchCraft"
author = "Bertha?"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27902cd6b70aa759a167afa33b8912af34c46c5cdf425e1f6cd5f9a926f1c4ce"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
