name = "witchCraft"
author = "Bertha?"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb9989051cf477e45cb2adbc19e02656c92e7c3e379ae05660c02fa2cc7d54a3"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
